# Generated by Django 2.1.2 on 2018-12-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0013_auto_20181208_0240'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sugang.Subject'),
        ),
    ]
