# Generated by Django 2.1.2 on 2018-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_board_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload_file/', verbose_name='파일첨부'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='제목'),
        ),
    ]
