# Generated by Django 2.1.2 on 2018-12-12 15:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20181213_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/upload/', location='/media/upload/'), upload_to='upload_file/', verbose_name='파일첨부'),
        ),
    ]
