# Generated by Django 2.1.2 on 2018-12-12 15:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20181213_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/upload/'), upload_to='', verbose_name='파일첨부'),
        ),
    ]
