# Generated by Django 2.1.2 on 2018-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecture_level',
            field=models.CharField(choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급'), ('공통', '공통')], default='공통', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_categorize',
            field=models.CharField(choices=[('토익', '토익'), ('토스', '토익 스피킹'), ('토플', '토플'), ('텝스', '텝스'), ('기초문법', '기초문법'), ('회화청취', '회화청취'), ('영작문', '영작문')], default='토익', max_length=10),
        ),
    ]
