# Generated by Django 2.1.2 on 2018-12-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0003_auto_20181206_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='take',
            old_name='u_id',
            new_name='username',
        ),
    ]
