# Generated by Django 2.1.2 on 2018-12-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0004_auto_20181207_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='sub_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sugang.Subject'),
            preserve_default=False,
        ),
    ]
