# Generated by Django 2.1.2 on 2018-12-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0005_take_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='sub_code',
            field=models.IntegerField(default=0),
        ),
    ]
