# Generated by Django 2.1.2 on 2018-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0006_auto_20181207_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='sub_code',
            field=models.CharField(max_length=10),
        ),
    ]
