# Generated by Django 2.1.2 on 2018-12-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0007_auto_20181207_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=10)),
                ('i_id', models.CharField(max_length=20)),
                ('i_code', models.CharField(max_length=10)),
                ('i_pw', models.CharField(max_length=30)),
            ],
        ),
    ]
