# Generated by Django 2.1.2 on 2018-12-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0011_auto_20181208_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='take',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
