# Generated by Django 2.1.2 on 2018-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0012_auto_20181208_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='i_name',
            new_name='name',
        ),
    ]
